theme: jekyll-theme-minimal
title: JOSÉ LUIS M. GONZÁLEZ //
logo: https://media-exp1.licdn.com/dms/image/C4D03AQHmqn0yxSERqg/profile-displayphoto-shrink_800_800/0/1622195623478?e=1641427200&v=beta&t=MmAKEK2r9PCyhqByCKRkP0uoAxqmALsTc2be0LQVZBo
